// Questions
export const SET_TOTAL = 'SET_TOTAL';
export const NEXT_QUESTION = 'NEXT_QUESTION';
export const UPDATE_ANSWER = 'UPDATE_ANSWER';
export const GOTO_QUESTION = 'GOTO_QUESTION';

// Payment
export const GET_CURRENCIES = 'GET_CURRENCIES';
export const GET_PROMOS = 'GET_PROMOS';
export const GET_PAYMENT_ADDRESS = 'GET_PAYMENT_ADDRESS';
export const SEND_PAYMENT = 'SEND_PAYMENT';
export const FORCE_ACCEPT_PAYMENT = 'FORCE_ACCEPT_PAYMENT';
